#include "adc.h"

/* Default ADC clock and prescaler */
#define ADC_CLOCK_SOURCE_DEFAULT        ADC_ACLK
#define ADC_CLOCK_PRESCALER_DEFAULT     ADC_CLOCK_PCLK_DIV2
#define ADC_SAMPLING_TIME_DEFAULT       ADC_SAMPLETIME_16CYCLES
#define ADC_SAMPLING_RATE_DEFAULT       ADC_SAMPLERATE_50KSPS
