#ifndef __TIMER_A_CONFIG_H
#define __TIMER_A_CONFIG_H

#include "timer_a.h"

#define TIMER_CLK_SRC_DEFAULT           TIMER_TACLK_CLOCK_SOURCE
#define TIMER_INPUT_DIVIDER_DEFAULT     TIMER_INPUT_DIV2
#define TIMER_MODE_CONTROL_DEFAULT      TIMER_UP_MODE

#endif // __TIMER_A_CONFIG_H